// 论文数据
const papersData = [
    {
        "year": 2020,
        "title": "Palettailor: Discriminable Colorization for Categorical Data",
        "venue": "IEEE Transactions on Visualization and Computer Graphics",
        "venueType": "期刊",
        "venueLevel": "CCF A类期刊",
        "venueFullName": "IEEE Transactions on Visualization and Computer Graphics (Proc. InfoVis 2020)",
        "authorPosition": "一作",
        "doi": "10.1109/TVCG.2020.3030406",
        "doiUrl": "https://doi.org/10.1109/TVCG.2020.3030406",
        "demoUrl": "https://iamkecheng.github.io/palettailor/",
        "demoUrlText": "在线网站",
        "techStack": "Javascript，D3，jQuery",
        "description": "提出了一种为不同可视化图表着色的通用方法，适用于多类散点图、折线图和直方图。现有的解决方案将颜色生成独立于颜色分配之外，我们的方法通过将数据的空间分布考虑在内，生成符合数据特征的调色板，提升了类间的区分度。",
        "volume": 27,
        "issue": 2,
        "pages": "475-484",
        "publicationDate": "Feb. 2021"
    },
    {
        "year": 2023,
        "title": "Interactive Context-preserving Color Highlighting for Multiclass Scatterplots",
        "venue": "CHI Conference on Human Factors in Computing Systems",
        "venueType": "会议",
        "venueLevel": "CCF A类会议",
        "venueFullName": "Proceedings of the 2023 CHI Conference on Human Factors in Computing Systems",
        "authorPosition": "一作",
        "doi": "10.1145/3544548.3580734",
        "doiUrl": "https://doi.org/10.1145/3544548.3580734",
        "demoUrl": "https://iamkecheng.github.io/palettailor/highlighting/demo/",
        "demoUrlText": "在线网站",
        "techStack": "Javascript，D3，jQuery",
        "description": "在Palettailor的基础上，我们进一步提出了适用于交互式操作的保持上下文信息的自动化调色板生成方法。该方法可以自动为给定数据生成两套具有高区分度的调色板，在交互过程中实时组合颜色以高亮不同部分，并保证剩余部分的区分度，在交互过程中为用户提供了更多操作指引，增强了数据探索效率。适用于多类散点图、折线图和直方图。",
        "pages": "1-15"
    },
    {
        "year": 2024,
        "title": "Color-Name Aware Optimization to Enhance the Perception of Transparent Overlapped Charts",
        "venue": "IEEE Transactions on Visualization and Computer Graphics",
        "venueType": "期刊",
        "venueLevel": "CCF A类期刊",
        "venueFullName": "IEEE Transactions on Visualization and Computer Graphics",
        "authorPosition": "一作",
        "doi": "10.1109/TVCG.2024.3520219",
        "doiUrl": "https://doi.org/10.1109/TVCG.2024.3520219",
        "demoUrl": "https://anon-link.github.io/transparency/",
        "demoUrlText": "在线网站",
        "techStack": "Javascript，D3，jQuery",
        "description": "提出了适用于半透明渲染的颜色分配及透明度自动优化算法，可有效减少由于透明度混合产生的新颜色导致的数据误解与歧义",
        "volume": 31,
        "issue": 9,
        "pages": "6617 - 6632",
        "publicationDate": "Dec. 2024"
    },
    {
        "year": 2025,
        "title": "C3-palette: Co-saliency based colorization for comparing categorical visualizations",
        "venue": "Computers & Graphics",
        "venueType": "期刊",
        "venueLevel": "CCF C类期刊，SCIE",
        "venueFullName": "Computers & Graphics",
        "authorPosition": "一作",
        "doi": "10.1016/j.cag.2025.104379",
        "doiUrl": "https://doi.org/10.1016/j.cag.2025.104379",
        "demoUrl": null,
        "demoUrlText": null,
        "techStack": "Javascript，D3，jQuery",
        "description": "提出了适用于比较分类数据可视化的颜色映射自动生成方法，通过计算数据项间的共显著性，生成具有高区分度的颜色映射，并适用于多类散点图、折线图和直方图。",
        "volume": 132,
        "issue": null,
        "pages": null,
        "publicationDate": "Aug. 2025"
    },
    {
        "year": 2019,
        "title": "A unified framework for exploring time-varying volumetric data based on block correspondence",
        "venue": "Visual Informatics",
        "venueType": "期刊",
        "venueLevel": "ESCI",
        "venueFullName": "Visual Informatics",
        "authorPosition": "一作",
        "doi": "10.1016/j.visinf.2019.10.001",
        "doiUrl": "https://doi.org/10.1016/j.visinf.2019.10.001",
        "demoUrl": null,
        "demoUrlText": null,
        "techStack": "实现了一整套时序体数据着色系统，包含系统界面、交互、计算及渲染模块，其中界面及交互使用Qt，核心计算使用Cuda 加速，渲染使用OpenGL 及Cg，可实现高质量的体绘制效果。",
        "description": "提出了适用于大规模时序体数据的统一框架，包含了关键帧提取、特征追踪和绘制参数自动生成等功能，核心是利用了GPU加速的BlockMatch算法，这是扩展自图形领域著名的PatchMatch算法，通过计算不同帧数据间密集的对应关系，实现细粒度的可视化参数自动生成。",
        "volume": 3,
        "issue": 4,
        "pages": "157-165"
    },
    {
        "year": 2022,
        "title": "Correlation-aware Probabilistic Data Summarization for Large-scale Multi-block Scientific Data Visualization",
        "venue": "Computational Visual Media",
        "venueType": "会议",
        "venueLevel": "CCF C类会议，SCIE",
        "venueFullName": "Computational Visual Media",
        "authorPosition": "二作",
        "doi": "10.1007/s41095-022-0304-6",
        "doiUrl": "https://doi.org/10.1007/s41095-022-0304-6",
        "demoUrl": null,
        "demoUrlText": null,
        "techStack": "C++",
        "description": "大规模科学数据由于存储规模较大，通常需要进行数据的轻量化以获得原始数据的参数表达。现有的方法基于统计分布模型实现了一到两个数量级的数据约减，但由于没有考虑数据块间的相关性，导致数据重建效果不连续。我们使用Copula函数改善了现有算法，显著增强了在相同参数设置下的重建效果，并适用于多块拼接的网格结构。",
        "volume": 9,
        "issue": 3,
        "pages": "513-529",
        "publicationDate": "2023"
    },
    {
        "year": 2024,
        "title": "Color Maker: a Mixed-Initiative Approach to Creating Accessible ColorMaps",
        "venue": "CHI Conference on Human Factors in Computing Systems",
        "venueType": "会议",
        "venueLevel": "CCF A类会议",
        "venueFullName": "CHI '24: Proceedings of the CHI Conference on Human Factors in Computing Systems",
        "authorPosition": "二作",
        "doi": "10.1145/3613904.3642265",
        "doiUrl": "https://doi.org/10.1145/3613904.3642265",
        "demoUrl": "https://colormaker.org/",
        "demoUrlText": "在线网站",
        "techStack": null,
        "description": "提出了适用于创建通用型颜色映射的混合式方法，通过结合用户偏好和数据特征，生成符合用户需求的颜色映射。",
        "articleNo": "145",
        "pages": "1 - 17"
    },
    {
        "year": 2025,
        "title": "Seeing Through the Overlap: The Impact of Color and Opacity on Depth Order Perception in Visualization",
        "venue": "CHI Conference on Human Factors in Computing Systems",
        "venueType": "会议",
        "venueLevel": "CCF A类会议",
        "venueFullName": "CHI '25: Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems",
        "authorPosition": "四作",
        "doi": "10.1145/3706598.3714070",
        "doiUrl": "https://doi.org/10.1145/3706598.3714070",
        "demoUrl": null,
        "demoUrlText": null,
        "techStack": null,
        "description": null,
        "articleNo": "1172",
        "pages": "1 - 14"
    },
    {
        "year": 2025,
        "title": "Visualization-Driven Illumination for Density Plots",
        "venue": "IEEE Transactions on Visualization and Computer Graphics",
        "venueType": "期刊",
        "venueLevel": "CCF A类期刊",
        "venueFullName": "IEEE Transactions on Visualization and Computer Graphics",
        "authorPosition": "四作",
        "doi": "10.1109/TVCG.2024.3495695",
        "doiUrl": "https://doi.org/10.1109/TVCG.2024.3495695",
        "demoUrl": null,
        "demoUrlText": null,
        "techStack": null,
        "description": null,
        "volume": 31,
        "issue": 2,
        "pages": "1631-1644",
        "publicationDate": "Feb. 2025"
    },
    {
        "year": 2025,
        "title": "Bi-Scale density-plot enhancement based on variance-aware filter",
        "venue": "Computers & Graphics",
        "venueType": "期刊",
        "venueLevel": "CCF C类期刊，SCIE",
        "venueFullName": "Computers & Graphics",
        "authorPosition": "三作",
        "doi": "10.1016/j.cag.2025.104180",
        "doiUrl": "https://doi.org/10.1016/j.cag.2025.104180",
        "demoUrl": null,
        "demoUrlText": null,
        "techStack": null,
        "description": null,
        "volume": 127,
        "issue": null,
        "pages": null,
        "publicationDate": "Feb. 2025"
    },
    {
        "year": 2019,
        "title": "VEGA: visual comparison of phylogenetic trees for evolutionary genome analysis",
        "venue": "Journal of Visualization",
        "venueType": "期刊",
        "venueLevel": "SCIE",
        "venueFullName": "Journal of Visualization",
        "authorPosition": "三作",
        "doi": "10.1007/s12650-020-00635-0",
        "doiUrl": "https://doi.org/10.1007/s12650-020-00635-0",
        "demoUrl": null,
        "demoUrlText": null,
        "techStack": null,
        "description": null,
        "volume": 23,
        "issue": 3,
        "pages": "523-537",
        "publicationDate": "2020"
    },
    {
        "year": 2017,
        "title": "Revisiting Stress Majorization as a Unified Framework for Interactive Constrained Graph Visualization",
        "venue": "IEEE Transactions on Visualization and Computer Graphics",
        "venueType": "期刊",
        "venueLevel": "CCF A类期刊",
        "venueFullName": "IEEE Transactions on Visualization and Computer Graphics (Proc. InfoVis 2017)",
        "authorPosition": "四作",
        "doi": "10.1109/TVCG.2017.2745919",
        "doiUrl": "https://doi.org/10.1109/TVCG.2017.2745919",
        "demoUrl": null,
        "demoUrlText": null,
        "techStack": null,
        "description": null,
        "volume": 24,
        "issue": 1,
        "pages": "489-499",
        "publicationDate": "Jan. 2018"
    }
];

